// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockFloat64UpDownCounter is an autogenerated mock type for the Float64UpDownCounter type
type MockFloat64UpDownCounter struct {
	mock.Mock
}

type MockFloat64UpDownCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64UpDownCounter) EXPECT() *MockFloat64UpDownCounter_Expecter {
	return &MockFloat64UpDownCounter_Expecter{mock: &_m.Mock}
}

// float64UpDownCounter provides a mock function with no fields
func (_m *MockFloat64UpDownCounter) float64UpDownCounter() {
	_m.Called()
}

// MockFloat64UpDownCounter_float64UpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64UpDownCounter'
type MockFloat64UpDownCounter_float64UpDownCounter_Call struct {
	*mock.Call
}

// float64UpDownCounter is a helper method to define mock.On call
func (_e *MockFloat64UpDownCounter_Expecter) float64UpDownCounter() *MockFloat64UpDownCounter_float64UpDownCounter_Call {
	return &MockFloat64UpDownCounter_float64UpDownCounter_Call{Call: _e.mock.On("float64UpDownCounter")}
}

func (_c *MockFloat64UpDownCounter_float64UpDownCounter_Call) Run(run func()) *MockFloat64UpDownCounter_float64UpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64UpDownCounter_float64UpDownCounter_Call) Return() *MockFloat64UpDownCounter_float64UpDownCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64UpDownCounter_float64UpDownCounter_Call) RunAndReturn(run func()) *MockFloat64UpDownCounter_float64UpDownCounter_Call {
	_c.Run(run)
	return _c
}

// NewMockFloat64UpDownCounter creates a new instance of MockFloat64UpDownCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64UpDownCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64UpDownCounter {
	mock := &MockFloat64UpDownCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
