// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockFloat64Histogram is an autogenerated mock type for the Float64Histogram type
type MockFloat64Histogram struct {
	mock.Mock
}

type MockFloat64Histogram_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64Histogram) EXPECT() *MockFloat64Histogram_Expecter {
	return &MockFloat64Histogram_Expecter{mock: &_m.Mock}
}

// float64Histogram provides a mock function with no fields
func (_m *MockFloat64Histogram) float64Histogram() {
	_m.Called()
}

// MockFloat64Histogram_float64Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Histogram'
type MockFloat64Histogram_float64Histogram_Call struct {
	*mock.Call
}

// float64Histogram is a helper method to define mock.On call
func (_e *MockFloat64Histogram_Expecter) float64Histogram() *MockFloat64Histogram_float64Histogram_Call {
	return &MockFloat64Histogram_float64Histogram_Call{Call: _e.mock.On("float64Histogram")}
}

func (_c *MockFloat64Histogram_float64Histogram_Call) Run(run func()) *MockFloat64Histogram_float64Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Histogram_float64Histogram_Call) Return() *MockFloat64Histogram_float64Histogram_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Histogram_float64Histogram_Call) RunAndReturn(run func()) *MockFloat64Histogram_float64Histogram_Call {
	_c.Run(run)
	return _c
}

// NewMockFloat64Histogram creates a new instance of MockFloat64Histogram. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64Histogram(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64Histogram {
	mock := &MockFloat64Histogram{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
