// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockFloat64Gauge is an autogenerated mock type for the Float64Gauge type
type MockFloat64Gauge struct {
	mock.Mock
}

type MockFloat64Gauge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64Gauge) EXPECT() *MockFloat64Gauge_Expecter {
	return &MockFloat64Gauge_Expecter{mock: &_m.Mock}
}

// float64Gauge provides a mock function with no fields
func (_m *MockFloat64Gauge) float64Gauge() {
	_m.Called()
}

// MockFloat64Gauge_float64Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Gauge'
type MockFloat64Gauge_float64Gauge_Call struct {
	*mock.Call
}

// float64Gauge is a helper method to define mock.On call
func (_e *MockFloat64Gauge_Expecter) float64Gauge() *MockFloat64Gauge_float64Gauge_Call {
	return &MockFloat64Gauge_float64Gauge_Call{Call: _e.mock.On("float64Gauge")}
}

func (_c *MockFloat64Gauge_float64Gauge_Call) Run(run func()) *MockFloat64Gauge_float64Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Gauge_float64Gauge_Call) Return() *MockFloat64Gauge_float64Gauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Gauge_float64Gauge_Call) RunAndReturn(run func()) *MockFloat64Gauge_float64Gauge_Call {
	_c.Run(run)
	return _c
}

// NewMockFloat64Gauge creates a new instance of MockFloat64Gauge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64Gauge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64Gauge {
	mock := &MockFloat64Gauge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
