// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockInt64Counter is an autogenerated mock type for the Int64Counter type
type MockInt64Counter struct {
	mock.Mock
}

type MockInt64Counter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64Counter) EXPECT() *MockInt64Counter_Expecter {
	return &MockInt64Counter_Expecter{mock: &_m.Mock}
}

// int64Counter provides a mock function with no fields
func (_m *MockInt64Counter) int64Counter() {
	_m.Called()
}

// MockInt64Counter_int64Counter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'int64Counter'
type MockInt64Counter_int64Counter_Call struct {
	*mock.Call
}

// int64Counter is a helper method to define mock.On call
func (_e *MockInt64Counter_Expecter) int64Counter() *MockInt64Counter_int64Counter_Call {
	return &MockInt64Counter_int64Counter_Call{Call: _e.mock.On("int64Counter")}
}

func (_c *MockInt64Counter_int64Counter_Call) Run(run func()) *MockInt64Counter_int64Counter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInt64Counter_int64Counter_Call) Return() *MockInt64Counter_int64Counter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInt64Counter_int64Counter_Call) RunAndReturn(run func()) *MockInt64Counter_int64Counter_Call {
	_c.Run(run)
	return _c
}

// NewMockInt64Counter creates a new instance of MockInt64Counter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64Counter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64Counter {
	mock := &MockInt64Counter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
