// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockInt64Observer is an autogenerated mock type for the Int64Observer type
type MockInt64Observer struct {
	mock.Mock
}

type MockInt64Observer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64Observer) EXPECT() *MockInt64Observer_Expecter {
	return &MockInt64Observer_Expecter{mock: &_m.Mock}
}

// int64Observer provides a mock function with no fields
func (_m *MockInt64Observer) int64Observer() {
	_m.Called()
}

// MockInt64Observer_int64Observer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'int64Observer'
type MockInt64Observer_int64Observer_Call struct {
	*mock.Call
}

// int64Observer is a helper method to define mock.On call
func (_e *MockInt64Observer_Expecter) int64Observer() *MockInt64Observer_int64Observer_Call {
	return &MockInt64Observer_int64Observer_Call{Call: _e.mock.On("int64Observer")}
}

func (_c *MockInt64Observer_int64Observer_Call) Run(run func()) *MockInt64Observer_int64Observer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInt64Observer_int64Observer_Call) Return() *MockInt64Observer_int64Observer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInt64Observer_int64Observer_Call) RunAndReturn(run func()) *MockInt64Observer_int64Observer_Call {
	_c.Run(run)
	return _c
}

// NewMockInt64Observer creates a new instance of MockInt64Observer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64Observer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64Observer {
	mock := &MockInt64Observer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
