// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockMeterProvider is an autogenerated mock type for the MeterProvider type
type MockMeterProvider struct {
	mock.Mock
}

type MockMeterProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMeterProvider) EXPECT() *MockMeterProvider_Expecter {
	return &MockMeterProvider_Expecter{mock: &_m.Mock}
}

// meterProvider provides a mock function with no fields
func (_m *MockMeterProvider) meterProvider() {
	_m.Called()
}

// MockMeterProvider_meterProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'meterProvider'
type MockMeterProvider_meterProvider_Call struct {
	*mock.Call
}

// meterProvider is a helper method to define mock.On call
func (_e *MockMeterProvider_Expecter) meterProvider() *MockMeterProvider_meterProvider_Call {
	return &MockMeterProvider_meterProvider_Call{Call: _e.mock.On("meterProvider")}
}

func (_c *MockMeterProvider_meterProvider_Call) Run(run func()) *MockMeterProvider_meterProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMeterProvider_meterProvider_Call) Return() *MockMeterProvider_meterProvider_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMeterProvider_meterProvider_Call) RunAndReturn(run func()) *MockMeterProvider_meterProvider_Call {
	_c.Run(run)
	return _c
}

// NewMockMeterProvider creates a new instance of MockMeterProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMeterProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMeterProvider {
	mock := &MockMeterProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
