// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// observer provides a mock function with no fields
func (_m *MockObserver) observer() {
	_m.Called()
}

// MockObserver_observer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'observer'
type MockObserver_observer_Call struct {
	*mock.Call
}

// observer is a helper method to define mock.On call
func (_e *MockObserver_Expecter) observer() *MockObserver_observer_Call {
	return &MockObserver_observer_Call{Call: _e.mock.On("observer")}
}

func (_c *MockObserver_observer_Call) Run(run func()) *MockObserver_observer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObserver_observer_Call) Return() *MockObserver_observer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObserver_observer_Call) RunAndReturn(run func()) *MockObserver_observer_Call {
	_c.Run(run)
	return _c
}

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
