// Code generated by mockery v2.50.0. DO NOT EDIT.

package embedded

import mock "github.com/stretchr/testify/mock"

// MockTracer is an autogenerated mock type for the Tracer type
type MockTracer struct {
	mock.Mock
}

type MockTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracer) EXPECT() *MockTracer_Expecter {
	return &MockTracer_Expecter{mock: &_m.Mock}
}

// tracer provides a mock function with no fields
func (_m *MockTracer) tracer() {
	_m.Called()
}

// MockTracer_tracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'tracer'
type MockTracer_tracer_Call struct {
	*mock.Call
}

// tracer is a helper method to define mock.On call
func (_e *MockTracer_Expecter) tracer() *MockTracer_tracer_Call {
	return &MockTracer_tracer_Call{Call: _e.mock.On("tracer")}
}

func (_c *MockTracer_tracer_Call) Run(run func()) *MockTracer_tracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTracer_tracer_Call) Return() *MockTracer_tracer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTracer_tracer_Call) RunAndReturn(run func()) *MockTracer_tracer_Call {
	_c.Run(run)
	return _c
}

// NewMockTracer creates a new instance of MockTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracer {
	mock := &MockTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
